language: node_js
node_js:
  - "stable"

services:
  - postgresql

install:
 - npm install

cache:
  directories:
    - "node_modules"

before_script:
  - psql -c "create database \"Questioner-test\";" -U postgres
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

script:
  - npm run migrate:drop
  - npm run migrate-only
  - npm run seed
  - npm test

after_success:
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
